spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


    filters: stat,wall    # 底层开启功能，wall 开启防火墙，stat  (sql监控)
    max-active: 10
    druid:
      filters: wall,stat

      stat-view-servlet:  # 配置监控页
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      aop-patterns: cn.neu.admin  # 监控springBean
      filter:
        stat:   # 对上面filters的详细配置
          slow-sql-millis: 1000     # 慢查询时间ms
          log-slow-sql: true        # 记录慢查询日志
        wall:
          enabled: true
          config:
            drop-table-allow: false  # 不允许删表
  jdbc:
    template:
      query-timeout: 3

# mybatis 配置
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml  # mybatis 全局配置文件  下面配置了configuration 就不需要指定全局配置文件
  mapper-locations: classpath:mybatis/mapper/**.xml          # sql映射文件

  configuration:    # 有了这里的配置，就不要指定mybatis的全局配置文件
    map-underscore-to-camel-case: true   # 开启驼峰命名规则

server:
  port: 8088
  tomcat:

    uri-encoding: UTF-8
