spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

    filters: stat,wall
    max-active: 10
  jdbc:
    template:
      query-timeout: 3